#Site settings
title: DATOS.GOB.MXxxx
email: hola@datos.gob.mx
layout: default.html
description: > # this means to ignore newlines until "baseurl:"
  En datos.gob.mx puedes descargar y utilizar libremente datos abiertos fsadfadfafsd
  que el Gobierno de la República genera y recolecta.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: DatosGobMx
twitter_text: "Descarga y utiliza libremente datos abiertos que el Gobierno de la República genera y recolecta. @GobRep @DatosGobMx"
github_username:  mxabierto

# Lista de Colaboradores
collaborators:
  secretaria_salud:
    title: "Secretaria de Salud"
    site: "http://portal.salud.gob.mx/"
    logo_url: "logoSALUD_hoz-233x80.png"
  imco:
    title: "IMCO"
    site: "http://imco.org.mx/home/"
    logo_url: "IMCO_presidencia-205x80.jpg"
  data4:
    title: "Data4"
    site: ""
    logo_url: "D4_Logo-80x80.png"
  inegi_facil:
    title: "INEGI Fácil"
    site: ""
    logo_url: "logo_160-80x80.png"
  cartografica:
    title: "Cartográfica"
    site: "http://cartografica.mx/"
    logo_url: "logo_cartografica-72-57x80.png"

# Build settings
markdown: kramdown
gems: ['jekyll-redirect-from']
jekyll_timeago:
  depth: 1 # Level of detail
  today: 'hoy'
  yesterday: 'ayer'
  tomorrow: 'mañana'
  and: 'y'
  suffix: ''
  prefix: 'hace'
  suffix_future: 'en'
  prefix_future: ''
  years: 'años'
  year: 'año'
  months: 'meses'
  month: 'mes'
  weeks: 'semanas'
  week: 'semana'
  days: 'dias'
  day: 'dia'
